"""Rotor-speed tracking stack: VK order tracking, refinement, blind seeding.

Pure array code (numpy/scipy/torch). This package must not import
``data_processing``, ``models``, or ``training`` — see ``AGENTS.md``.
"""

from tracking.comb_displacement import (
    DisplacementConfig,
    carrier_collision_mask,
    demod_comb_bank,
    measure_variant,
    nearest_interloper_hz,
    pulse_pair,
    pulse_pair_bank,
)
from tracking.dsp import boxcar, demod, dsp_config, thread_pool, zoom_bands
from tracking.fitness import (
    CONTROLS,
    Cells,
    FitnessConfig,
    FitnessScore,
    Holdout,
    apply_control,
    bootstrap_scores,
    fitness_stage,
    residual_decompose,
    score_cells,
    score_window,
    window_cells,
)
from tracking.joint_beam_tracker import build_objective, joint_beam_track
from tracking.order_domain import (
    OrderSpectrum,
    comb_scan,
    order_spectrum,
    peak_orders,
    scan_summary,
    segment_comb_scan,
)
from tracking.phase_increment_tracker import demod_bank, pi_kalman_refine
from tracking.phase_noise import Arm, arm_covariance, demod_rotor, fit_rank_one
from tracking.pipelines import (
    ARMS,
    CAPTURE_CFG,
    DEFAULT_PEEL_MODE,
    MIDBAND_CFG,
    MIDBAND_CFGS,
    PEEL_MODES,
    PI_VARIANTS,
    REFINE_CFG,
    SEED_CFG,
    TRACK_CFG,
    make_peels,
    peel_alternation,
    pi_kalman_arm_stage,
    vit2dsp_pipeline,
    vit2dsp_stage,
)
from tracking.protocols import (
    BEATVK,
    PROTOCOLS,
    VK37,
    PoolSpec,
    ProtocolSpec,
    WindowSpec,
    get_protocol,
    iter_windows,
    to_frame,
)
from tracking.rotor_dp import greedy_peel, viterbi_path
from tracking.rps_refinement import (
    RefineConfig,
    comb_confidence,
    compute_logmag,
    estimate_clock_offset,
    refine_coherent,
    refine_trajectories,
)
from tracking.stages import (
    DEFAULT_HOP_S,
    Stage,
    blind_seed_stage,
    get_audio,
    get_rps,
    guarded,
    pi_kalman_stage,
    pipeline,
    refine_coherent_stage,
    tracking_frame,
    vk_stage,
    warp_stage,
    with_rps,
)
from tracking.telemetry_refit import (
    RefitConfig,
    RefitResult,
    k_cap_for_error,
    order_and_gaps,
    presmooth,
    refit_stage,
    refit_window,
    scale_summary,
)
from tracking.vk_blind_seeding import SeedConfig, blind_seed, stage_guard, whitened_logmag
from tracking.vk_tracking import (
    VKConfig,
    demodulate,
    ls_project_envelopes,
    vk_envelopes,
    vk_reconstruct,
    vk_track,
)
from tracking.warp_refinement import iter_warp_refine

__all__ = [
    "RefitConfig",
    "RefitResult",
    "k_cap_for_error",
    "order_and_gaps",
    "presmooth",
    "refit_stage",
    "refit_window",
    "scale_summary",
    "pulse_pair_bank",
    "pulse_pair",
    "window_cells",
    "score_window",
    "score_cells",
    "residual_decompose",
    "fitness_stage",
    "bootstrap_scores",
    "apply_control",
    "Holdout",
    "FitnessScore",
    "FitnessConfig",
    "Cells",
    "CONTROLS",
    "ARMS",
    "Arm",
    "BEATVK",
    "CAPTURE_CFG",
    "DEFAULT_HOP_S",
    "DEFAULT_PEEL_MODE",
    "DisplacementConfig",
    "MIDBAND_CFG",
    "MIDBAND_CFGS",
    "OrderSpectrum",
    "PEEL_MODES",
    "PI_VARIANTS",
    "PROTOCOLS",
    "PoolSpec",
    "ProtocolSpec",
    "REFINE_CFG",
    "RefineConfig",
    "SEED_CFG",
    "SeedConfig",
    "Stage",
    "TRACK_CFG",
    "VK37",
    "VKConfig",
    "WindowSpec",
    "arm_covariance",
    "blind_seed",
    "blind_seed_stage",
    "build_objective",
    "carrier_collision_mask",
    "comb_confidence",
    "comb_scan",
    "compute_logmag",
    "boxcar",
    "demod",
    "demod_bank",
    "demod_comb_bank",
    "demod_rotor",
    "demodulate",
    "estimate_clock_offset",
    "dsp_config",
    "fit_rank_one",
    "get_audio",
    "get_protocol",
    "get_rps",
    "greedy_peel",
    "guarded",
    "iter_warp_refine",
    "iter_windows",
    "joint_beam_track",
    "ls_project_envelopes",
    "make_peels",
    "measure_variant",
    "nearest_interloper_hz",
    "order_spectrum",
    "peak_orders",
    "peel_alternation",
    "pi_kalman_arm_stage",
    "pi_kalman_refine",
    "pi_kalman_stage",
    "pipeline",
    "refine_coherent",
    "refine_coherent_stage",
    "refine_trajectories",
    "scan_summary",
    "segment_comb_scan",
    "stage_guard",
    "to_frame",
    "tracking_frame",
    "vit2dsp_pipeline",
    "vit2dsp_stage",
    "viterbi_path",
    "vk_envelopes",
    "vk_reconstruct",
    "vk_stage",
    "vk_track",
    "warp_stage",
    "whitened_logmag",
    "thread_pool",
    "with_rps",
    "zoom_bands",
]
